# When a new tag is created, it will build server and agents with that tag as version.
# eg. 1.2.34
name: Build

on:
  push:
    tags:
       - '*'

jobs:
# #########################################
# Build Server
# #########################################
  build:
    env:
      PATH_BASE: ${{github.workspace}}
      PATH_BASE_APP: ${{github.workspace}}/BetterAppSettings
      APP_NAME: BetterAppSettings
      VERSION_DOTNET: '5.0'

    runs-on: ubuntu-latest
    steps:
      # #########################################
      # Setup
      # #########################################
      - uses: actions/checkout@v2

      - name: Get TAG version
        run: |
          echo "TAG_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "Version '${GITHUB_REF/refs\/tags\//}'"
        shell: bash

      - name: Debug
        run: |
          ls

      # #########################################
      # Publish NuGet
      # #########################################
      - name: Publish to NuGet
        id: publish_nuget
        uses: alexandredubois/publish-nuget@Include-version-in-nupkgfile-name
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: ${{env.APP_NAME}}/${{env.APP_NAME}}/${{env.APP_NAME}}.csproj

          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: ${{env.APP_NAME}}

          # Filepath with version info, relative to root of repository & defaults to PROJECT_FILE_PATH
          # VERSION_FILE_PATH: Directory.Build.props

          # Regex pattern to extract version info in a capturing group
          # VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$

          # Useful with external providers like Nerdbank.GitVersioning, ignores VERSION_FILE_PATH & VERSION_REGEX
          VERSION_STATIC: ${{env.TAG_VERSION}}

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false

          # Format of the git tag, [*] gets replaced with actual version
          # TAG_FORMAT: '*'

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.NUGET_KEY}}

          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          NUGET_SOURCE: https://api.nuget.org

          # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
          INCLUDE_SYMBOLS: false